### ISSUE TITLE
[New Feature Request] Will support horizontal mode ?

### ISSUE THREAD

**Issue by SwordMaA** [stavgafny/wheel_picker#1]
Hi, this wheel picker widget helped me a lot. But I also need it to be horizontally displayed. Do you have any plan to support it ?

Thanks.

**Comment by stavgafny** [comment]
Hey @ZhiwenLuoAllIn,
Thank you for using this package, i'm glad you found it useful.
I will absolutely add it in the next version, currently I am a bit busy so it might take me a while.

If you want you can also add this feature, the current code is quite simple and intuitive so it shouldn't take long to add it.

I will make sure to keep you updated in the meantime.

**Comment by stavgafny** [comment]
Hey @ZhiwenLuoAllIn,

I wanted to let you know that I've updated the package and added support for the horizontal scroll feature.
Feel free to check out the latest version and confirm if everything is working as expected. If you have any further feedback or questions, please don't hesitate to reach out.

Hope it helps!

**Comment by stavgafny** [comment]
I'm closing this issue as the feature has been added. If you come across any issues with the implementation, please let me know.
