### ISSUE TITLE
about the spacing between items

### ISSUE THREAD

**Issue by yellowfisherz** [stavgafny/wheel_picker#3]
![image](https://github.com/stavgafny/wheel_picker/assets/46810677/6bc2714a-f172-464e-acf8-b0fa3e3e480d)
```
WheelPickerStyle(
  size: 300,
  itemExtent: 75,
  squeeze: 1,
  diameterRatio: 5,
  surroundingOpacity: .5,
  magnification: 1.2,
),
```
If  set the itemExtent too small, the text will be forced to wrap, resulting in incomplete display. If set the itemExtent too large, the items will become very tall. How can you ensure the text is displayed properly while keeping the items close to each other?
itemExtent seems to constrain it into a square?

**Comment by stavgafny** [comment]
Hey @yellowfisherz,

I'm familiar with this issue and have a couple of solutions in mind.

Currently, the wheel width is calculated as `itemExtent * magnification`.

1. **Removing Width Cap:** This gives developers full control over the width, but it might cause a `RenderConstrainedBox` if certain constraints aren't met.
2. **Using `IntrinsicWidth`** This sets the wheel's width to the child with the maximum width. However, this solution can be relatively expensive, getting to O(N²) in the worst case.

Let me know which one you think will be most preferred or if you have any other solutions. A fix for that is indeed needed.

**Comment by yellowfisherz** [comment]
I'm sorry for the late reply. @stavgafny 
Currently, I think i need first solution, where the height and width of the item can be fully controlled by the developer. This solution meets my current needs.
Thanks.

**Comment by stavgafny** [comment]
Hey @yellowfisherz.
No worries, I also agree that the first solution would be the most fitting for most developers. I'll be adding it soon and will update you on the version release.

**Comment by stavgafny** [comment]
Hey @yellowfisherz,
I’m happy to let you know that a new version is now available, providing developers with full control over the sizing and constraints of the widget.

If you want to give it a try, here’s a small example of how it looks now:

```dart
import 'package:flutter/material.dart';
import 'package:wheel_picker/wheel_picker.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Example',
      theme: ThemeData.dark(useMaterial3: true),
      home: const Scaffold(
        body: Center(
          child: WheelPickerExample(),
        ),
      ),
    );
  }
}

class WheelPickerExample extends StatelessWidget {
  const WheelPickerExample({super.key});

  @override
  Widget build(BuildContext context) {
    const textStyle = TextStyle(fontSize: 36.0, height: 1.5);
    final wheelStyle = WheelPickerStyle(
      itemExtent: textStyle.fontSize! * textStyle.height!, // Text height
      squeeze: 1.25,
      diameterRatio: .8,
      surroundingOpacity: .25,
      magnification: 1.2,
    );

    return Center(
      child: WheelPicker(
        itemCount: 100,
        builder: (context, index) {
          return Text(
            "This is a long text $index",
            style: textStyle,
          );
        },
        selectedIndexColor: Colors.red[300],
        looping: false,
        style: wheelStyle,
      ),
    );
  }
}

```

**Comment by yellowfisherz** [comment]
@stavgafny Its work!!!!Thanks bro!!!Your response speed is really impressive!!!
![image](https://github.com/user-attachments/assets/1e00c77f-3502-4461-abf3-8d0bed865ee9)

**Comment by stavgafny** [comment]
@yellowfisherz I'm happy you liked it and glad to hear it worked for you! I'll go ahead and close this issue. If you run into any further issues, feel free to open a new one. Thanks!
