### ISSUE TITLE
Feature Request: add width property

### ISSUE THREAD

**Issue by dizzib** [stavgafny/wheel_picker#4]
I understand from #3 and examining the source that wheel width is calculated as itemExtent * magnification.

Would it be possible to manually set the width please?

This is so I can have 2 WheelPickers side by side, one taking 80% and the other 20% of the parent widget width, each responding to touch gestures across their full widths if that makes sense.

Currently I cannot see a way to do this.

**Comment by stavgafny** [comment]
Hey @dizzib,

I agree that having the ability to manually adjust the width is important. I already have a straightforward solution in mind that won't break any existing WheelPickers and am planning to implement it in the upcoming days.

In the meantime, you can remove the `width` argument in the SizedBox wrapper inside the widget itself. This will throw a *`BoxConstraints`* exception if the width is not bounded in some way.

I'll make sure to notify you when the update is released.

**Comment by dizzib** [comment]
Thank you for your quick response.

I have decided to use the native ListWheelScrollView for now, because I was unable to get WheelPicker to refresh its contents when calling setState from onIndexChanged in another WheelPicker, not sure why 🤷.

Thanks anyway!👍

**Comment by stavgafny** [comment]
Hey @dizzib, 

If you want me to check that out I can try to see where it fails to update since it should work.

Either way I'll let you know when I release the update.

**Comment by dizzib** [comment]
Ok thanks, I may give it another try after you have released the update.

**Comment by stavgafny** [comment]
Hey @dizzib,
I’m happy to share that a new version is now available! It solves the issue you mentioned by giving developers full control over the widget's sizing and constraints.

If you ever want to try it again and see how it looks now, check out the example in Issue #3.
